//! The code-generated placeholder library (goal 61).
//!
//! Clearly temporary, top-down, readable at a glance, and without baked
//! cast shadows. Output is a pure function of the seed, so the committed
//! library can be regenerated byte for byte.

mod brush;
pub mod ground;
mod material;
pub mod paint;
mod props;
mod relief;
mod specs;
mod vegetation;
pub mod walls;

use crate::catalog::{
    Asset, AssetClass, Catalog, Cover, Footprint, Layer, PlacementRules, TagVocabulary, Tags,
    WallPiece, FORMAT_VERSION,
};
use crate::error::TacticalError;
use crate::library::CATALOG_FILE;
use crate::noise::hash_str;
use crate::raster::Rgba;
use std::collections::BTreeMap;
use std::path::Path;

/// Source resolution of the placeholder art.
pub const PPSQ: u32 = 128;
/// The default generation seed.
pub const DEFAULT_SEED: u64 = 58;
/// Licence string on every placeholder asset.
pub const LICENCE: &str = "Apache-2.0 (generated placeholder)";

pub(crate) fn base(
    id: &str,
    class: AssetClass,
    dir: &str,
    w: u32,
    h: u32,
    layer: Layer,
    seed: u64,
) -> Asset {
    Asset {
        id: id.to_string(),
        class,
        image: format!("{dir}/{id}.png"),
        footprint: Footprint { w, h },
        anchor: None,
        rotations: vec![0, 90, 180, 270],
        mirror: true,
        tags: Tags {
            biome: vec!["temperate".into()],
            culture: vec!["human".into()],
            ..Tags::default()
        },
        placement: PlacementRules::default(),
        blocks_sight: false,
        blocks_movement: false,
        difficult_terrain: false,
        cover: Cover::None,
        light: None,
        layer,
        z: 0,
        casts_shadow: false,
        height_ft: 0,
        tileable: false,
        ground: None,
        wall: None,
        provenance: format!("arda-tactical placeholder generator, seed {seed}"),
        licence: LICENCE.to_string(),
    }
}

fn ground_assets(seed: u64) -> Vec<(Asset, Rgba)> {
    let mut out = Vec::new();
    for (kind, variants, is_water) in ground::TYPES {
        for v in 0..variants {
            let id = format!("{}.{kind}.{v}", if is_water { "water" } else { "ground" });
            let (class, layer) = if is_water {
                (AssetClass::Water, Layer::Water)
            } else {
                (AssetClass::Ground, Layer::Ground)
            };
            let mut a = base(
                &id,
                class,
                "ground",
                ground::squares(kind),
                ground::squares(kind),
                layer,
                seed,
            );
            a.tileable = true;
            a.ground = Some(kind.to_string());
            a.difficult_terrain = matches!(
                kind,
                "mud"
                    | "mudflat"
                    | "water_shallow"
                    | "marsh"
                    | "reed_bed"
                    | "scree"
                    | "ice"
                    | "cliff"
            );
            a.blocks_movement = kind == "water_deep";
            if ground::STRUCTURED.contains(&kind) {
                a.tags.free.push("structured".into());
            }
            out.push((
                a,
                ground::texture(kind, hash_str(seed, &id), hash_str(seed, kind), PPSQ),
            ));
        }
    }
    out
}

fn wall_assets(seed: u64) -> Vec<(Asset, Rgba)> {
    let mut out = Vec::new();
    for kit in &walls::ALL_KITS {
        for role in walls::ROLES {
            let id = format!("wall.{}.{}", kit.name, role_name(role));
            let mut a = base(&id, AssetClass::Wall, "walls", 1, 1, Layer::Wall, seed);
            a.wall = Some(WallPiece {
                kit: kit.name.to_string(),
                role,
            });
            a.height_ft = kit.height_ft;
            a.casts_shadow = true;
            a.mirror = false;
            let solid = matches!(
                role,
                crate::catalog::WallRole::Run
                    | crate::catalog::WallRole::Door
                    | crate::catalog::WallRole::Gate
            ) || !role.is_edge();
            a.blocks_sight = solid;
            a.blocks_movement = solid || role == crate::catalog::WallRole::Window;
            a.cover = if solid {
                Cover::Full
            } else {
                Cover::ThreeQuarters
            };
            a.tags.function = kit_functions(kit.name)
                .iter()
                .map(|f| (*f).to_string())
                .collect();
            out.push((a, walls::piece(kit, role, hash_str(seed, &id), PPSQ)));
        }
    }
    out
}

/// Building functions a wall kit suits.
fn kit_functions(kit: &str) -> &'static [&'static str] {
    match kit {
        "stone" => &[
            "house",
            "warehouse",
            "manor",
            "temple",
            "library",
            "keep",
            "smithy",
            "mill",
        ],
        "timber" => &[
            "house",
            "farmhouse",
            "cottage",
            "inn",
            "tavern",
            "stable",
            "barn",
            "workshop",
            "bakery",
            "brewery",
            "boathouse",
        ],
        "wattle" => &["cottage", "farmhouse", "farm", "stall"],
        "palisade" => &["keep", "barracks", "farm"],
        "hedge" | "drystone" => &["farm", "street"],
        // Natural rock: no building function, so no tradition picks it.
        "cave" => &[],
        _ => &["keep", "guardhouse", "barracks", "street"],
    }
}

/// The snake-case name of a wall role, as used in ids.
#[must_use]
pub fn role_name(role: crate::catalog::WallRole) -> String {
    format!("{role:?}").to_lowercase()
}

/// Every building function in the shared vocabulary
/// (`docs/goal-prompts/vocabulary.md`).
pub const FUNCTIONS: [&str; 34] = [
    "house",
    "farmhouse",
    "cottage",
    "manor",
    "inn",
    "tavern",
    "bakery",
    "brewery",
    "mill",
    "smithy",
    "workshop",
    "tannery",
    "apothecary",
    "temple",
    "shrine",
    "library",
    "warehouse",
    "market",
    "stall",
    "dock",
    "boathouse",
    "keep",
    "barracks",
    "guardhouse",
    "stable",
    "barn",
    "street",
    "farm",
    "market_hall",
    "mine",
    "lumber_camp",
    "school",
    "toll_house",
    "waystation",
];

/// Generates the whole placeholder library in memory.
#[must_use]
pub fn generate(seed: u64) -> (Catalog, BTreeMap<String, Rgba>) {
    let mut pairs = ground_assets(seed);
    pairs.extend(wall_assets(seed));
    pairs.extend(
        specs::PROPS
            .iter()
            .map(|spec| specs::prop_asset(spec, seed)),
    );
    pairs.extend(vegetation::assets(seed));
    let words = |xs: &[&str]| xs.iter().map(|s| (*s).to_string()).collect();
    let catalog = Catalog {
        format_version: FORMAT_VERSION,
        library: "placeholder".into(),
        library_version: format!("0.1.0+seed{seed}"),
        pixels_per_square: PPSQ,
        vocabulary: TagVocabulary {
            biome: words(&["temperate", "boreal", "alpine", "wetland"]),
            culture: words(&["human"]),
            wealth: words(&["poor", "modest", "wealthy"]),
            function: words(&FUNCTIONS),
        },
        assets: pairs.iter().map(|(a, _)| a.clone()).collect(),
    };
    let images = pairs.into_iter().map(|(a, img)| (a.id, img)).collect();
    (catalog, images)
}

/// Writes the placeholder library to `dir` (catalogue plus PNGs).
///
/// # Errors
/// I/O and encoding failures.
pub fn write(dir: &Path, seed: u64) -> Result<Catalog, TacticalError> {
    let (catalog, images) = generate(seed);
    for a in &catalog.assets {
        if let Some(img) = images.get(&a.id) {
            img.write_png(&dir.join(&a.image))?;
        }
    }
    let json = crate::catalog::to_json(&catalog).map_err(|source| TacticalError::Catalog {
        path: dir.join(CATALOG_FILE),
        source,
    })?;
    let path = dir.join(CATALOG_FILE);
    std::fs::write(&path, json + "\n").map_err(|source| TacticalError::Io { path, source })?;
    Ok(catalog)
}

#[cfg(test)]
mod tests;
