// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the six abilities, in SRD order.
 */
export type Ability = "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
