// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable code, HTTP status and human message.
 */
export type ApiErrorBody = { 
/**
 * Stable code: `bad_request`, `out_of_range`, `not_found`, `no_block`, `payload_too_large`,
 * `unsupported_media_type`, `invalid_layout`, `resource_limit`, `not_implemented` or `internal`.
 */
code: string, 
/**
 * HTTP status repeated in the body.
 */
status: number, 
/**
 * Human-readable detail; not stable.
 */
message: string, };
