// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AreaColumns } from "./AreaColumns";
import type { Legend } from "./Legend";

/**
 * `/v1/area/{ax}/{ay}/cells` JSON body.
 */
export type AreaCells = { 
/**
 * Cell contract version.
 */
contract_version: number, 
/**
 * Area column.
 */
ax: number, 
/**
 * Area row.
 */
ay: number, 
/**
 * Global column of local x = 0.
 */
gx0: number, 
/**
 * Global row of local y = 0.
 */
gy0: number, 
/**
 * Columns per row (512).
 */
width: number, 
/**
 * Rows (512).
 */
height: number, 
/**
 * Enum code tables.
 */
legend: Legend, 
/**
 * Values.
 */
columns: AreaColumns, };
