// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LakeDto } from "./LakeDto";

/**
 * `/v1/area/{ax}/{ay}/lakes`.
 */
export type AreaLakes = { 
/**
 * Cell contract version.
 */
contract_version: number, 
/**
 * Area column.
 */
ax: number, 
/**
 * Area row.
 */
ay: number, 
/**
 * Lakes in stored order.
 */
lakes: Array<LakeDto>, };
