// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One array per [`CellSample`] field, each 512 × 512 long.
 */
export type AreaColumns = { 
/**
 *Elevation, m.
 */
height_m: Array<number>, 
/**
 *Terrain code ([`Legend::terrain`]).
 */
terrain: Array<number>, 
/**
 *Cover code ([`Legend::cover`]).
 */
cover: Array<number>, 
/**
 *Slope, degrees.
 */
slope_deg: Array<number>, 
/**
 *Downslope bearing, degrees.
 */
aspect_deg: Array<number>, 
/**
 *Mean annual temperature, °C.
 */
temperature_c: Array<number>, 
/**
 *Annual rainfall, mm.
 */
rainfall_mm: Array<number>, 
/**
 *Soil moisture, 0–1.
 */
moisture: Array<number>, 
/**
 *Standing-water tendency, 0–1.
 */
wetness: Array<number>, 
/**
 *Canopy closure, 0–1.
 */
forest_density: Array<number>, 
/**
 *Drainage area, km².
 */
drainage_area_km2: Array<number>, 
/**
 *Mean discharge, m³/s.
 */
discharge_m3s: Array<number>, 
/**
 *Strahler order, 0 = none.
 */
watercourse_order: Array<number>, 
/**
 *Channel width, m.
 */
watercourse_width_m: Array<number>, 
/**
 *Height above channel, m.
 */
height_above_river_m: Array<number>, 
/**
 *Road code ([`Legend::road`]).
 */
road: Array<number>, 
/**
 *Settlement id, 0 = none.
 */
built_by: Array<number>, 
/**
 *1 on coast cells.
 */
is_coast: Array<number>, 
/**
 *Coast distance, m; null beyond 5 km.
 */
coast_distance_m: Array<number | null>, 
/**
 *Snow proxy of the cell, 0–1.
 */
snow_fraction: Array<number>, 
/**
 *Snow proxy at the footprint peak.
 */
snow_peak_fraction: Array<number | null>, 
/**
 *1 when perennially snowed.
 */
snow_perennial: Array<number>, 
/**
 *Proxy snowline altitude, m.
 */
snowline_m: Array<number>, 
/**
 *Owning river segment id, 0 = none.
 */
river_segment: Array<number>, 
/**
 *Covering lake id, 0 = none.
 */
lake_id: Array<number>, 
/**
 *Lake depth of the cell, m.
 */
lake_depth_m: Array<number | null>, 
/**
 *Fine height at the cell centre, m.
 */
fine_centre_m: Array<number | null>, 
/**
 *Fine footprint minimum, m.
 */
fine_min_m: Array<number | null>, 
/**
 *Fine footprint maximum, m.
 */
fine_max_m: Array<number | null>, };
