// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiverDto } from "./RiverDto";

/**
 * `/v1/area/{ax}/{ay}/rivers`.
 */
export type AreaRivers = { 
/**
 * Cell contract version.
 */
contract_version: number, 
/**
 * Area column.
 */
ax: number, 
/**
 * Area row.
 */
ay: number, 
/**
 * Segments in stored order.
 */
rivers: Array<RiverDto>, };
