// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetClassDto } from "./AssetClassDto";

/**
 * An asset chosen by id or by a deterministic tag query.
 */
export type AssetRefDto = { "id": string } | { "query": { 
/**
 * Restrict to a class.
 */
class: AssetClassDto | null, 
/**
 * Required tags.
 */
tags: Array<string>, } };
