// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttackKind } from "./AttackKind";

/**
 * One attack line.
 */
export type Attack = { 
/**
 * Name.
 */
name: string, 
/**
 * Melee or ranged.
 */
kind: AttackKind, 
/**
 * Attack bonus.
 */
to_hit: number, 
/**
 * Damage dice.
 */
damage: string, 
/**
 * Average damage.
 */
average: number, 
/**
 * Damage type.
 */
damage_type: string, 
/**
 * Reach or range.
 */
range: string, 
/**
 * Extra effects.
 */
extra: Array<string>, };
