// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingFunction } from "./BuildingFunction";

/**
 * One building of a settlement.
 */
export type BuildingSpec = { 
/**
 * Building id, unique within the settlement.
 */
id: string, 
/**
 * Owning settlement id.
 */
settlement_id: string, 
/**
 * What the building is for.
 */
function: BuildingFunction, 
/**
 * Free tags such as `craft:weaving`; omitted when empty.
 */
tags?: Array<string>, 
/**
 * Resident capacity.
 */
capacity: number, 
/**
 * Workplace slots, master included.
 */
workplace_slots: number, 
/**
 * Building wealth, 0–255.
 */
wealth: number, };
