// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a building is for: a plain snake_case string (vocabulary I7).
 */
export type BuildingFunction = "house" | "farmhouse" | "cottage" | "manor" | "inn" | "tavern" | "bakery" | "brewery" | "mill" | "smithy" | "workshop" | "tannery" | "apothecary" | "temple" | "shrine" | "library" | "warehouse" | "market" | "stall" | "dock" | "boathouse" | "keep" | "barracks" | "guardhouse" | "stable" | "barn" | "street" | "farm" | "market_hall" | "mine" | "lumber_camp" | "school";
