// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoastSample } from "./CoastSample";
import type { CoverDto } from "./CoverDto";
import type { FineHeights } from "./FineHeights";
import type { LakeMembership } from "./LakeMembership";
import type { LandUseDto } from "./LandUseDto";
import type { RiverMembership } from "./RiverMembership";
import type { RoadDto } from "./RoadDto";
import type { SnowSample } from "./SnowSample";
import type { TerrainKindDto } from "./TerrainKindDto";

/**
 * Everything the world knows about one 100 m global cell, in plain units.
 */
export type CellSample = { 
/**
 * [`CONTRACT_VERSION`] this sample was produced under.
 */
contract_version: number, 
/**
 * Global cell column.
 */
gx: number, 
/**
 * Global cell row.
 */
gy: number, 
/**
 * Area tile column containing the cell.
 */
ax: number, 
/**
 * Area tile row containing the cell.
 */
ay: number, 
/**
 * Column within the area, 0–511.
 */
cx: number, 
/**
 * Row within the area, 0–511.
 */
cy: number, 
/**
 * West edge of the cell, metres east of the world origin (`gx·100`).
 */
x_m: number, 
/**
 * North edge of the cell, metres south of the world origin (`gy·100`).
 */
y_m: number, 
/**
 * Cell centre, metres east of the world origin (`gx·100 + 50`).
 */
centre_x_m: number, 
/**
 * Cell centre, metres south of the world origin (`gy·100 + 50`).
 */
centre_y_m: number, 
/**
 * Elevation above sea level, metres (`Cell::height`, mm).
 */
height_m: number, 
/**
 * Sea, land or lake (`Cell::terrain`).
 */
terrain: TerrainKindDto, 
/**
 * Dominant cover (`Cell::cover`).
 */
cover: CoverDto, 
/**
 * Slope, degrees (`Cell::slope_milli_deg`).
 */
slope_deg: number, 
/**
 * Downslope compass bearing, degrees 0–359; 0 on flat ground (`Cell::aspect_deg`).
 */
aspect_deg: number, 
/**
 * Mean annual temperature, °C (`Cell::temperature`, centi-°C).
 */
temperature_c: number, 
/**
 * Mean annual rainfall, mm (`Cell::rainfall`).
 */
rainfall_mm: number, 
/**
 * Soil moisture, 0–1 (`Cell::moisture` / 255).
 */
moisture: number, 
/**
 * Standing-water tendency, 0–1 (`Cell::wetness` / 255).
 */
wetness: number, 
/**
 * Canopy closure, 0–1 (`Cell::forest_density` / 255).
 */
forest_density: number, 
/**
 * Upstream drainage area, km² (`Cell::drainage_area_cells` × 0.01 km²).
 */
drainage_area_km2: number, 
/**
 * Mean discharge, m³/s (`Cell::discharge`, L/s).
 */
discharge_m3s: number, 
/**
 * Strahler order; 0 when no watercourse (`Cell::watercourse_order`).
 */
watercourse_order: number, 
/**
 * Channel width, metres; 0 when no watercourse (`Cell::watercourse_width_dm`).
 */
watercourse_width_m: number, 
/**
 * Height above the nearest downstream channel, metres (`Cell::height_above_river_dm`).
 */
height_above_river_m: number, 
/**
 * Road class: `society/roads.bin` when present, else `Cell::road`.
 */
road: RoadDto, 
/**
 * Settlement id (decimal string) that owns this cell: `society/landuse.bin`
 * owners when present, else `Cell::built_by`; `null` when none.
 */
built_by: string | null, 
/**
 * Land use (`society/landuse.bin`); `null` without a `society/`.
 */
land_use: LandUseDto | null, 
/**
 * Realm id (decimal string, `society/realms.bin`); `null` when none or
 * without a `society/`.
 */
realm_id: string | null, 
/**
 * Derived coast facts.
 */
coast: CoastSample, 
/**
 * Derived snow proxy.
 */
snow: SnowSample, 
/**
 * Saved river course through this cell, if any.
 */
river: RiverMembership | null, 
/**
 * Saved lake covering this cell, if any.
 */
lake: LakeMembership | null, 
/**
 * Fine-terrain heights; `null` for worlds without `terrain/fine.bin`.
 */
fine: FineHeights | null, };
