// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Derived coast facts.
 */
export type CoastSample = { 
/**
 * A land cell with at least one sea cell among its 8 neighbours.
 */
is_coast: boolean, 
/**
 * Euclidean centre-to-centre distance to the nearest coast cell, metres;
 * 0 on the coast, `null` when none lies within [`coast::MAX_DISTANCE_M`].
 */
distance_m: number | null, };
