// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coins carried.
 */
export type Coins = { 
/**
 * Gold.
 */
gp: number, 
/**
 * Silver.
 */
sp: number, 
/**
 * Copper.
 */
cp: number, };
