// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SRD 5.1 degrees of cover.
 */
export type CoverLevelDto = "none" | "half" | "three_quarters" | "total";
