// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dominant ground cover (source: `Cell::cover`, `logic/02` vegetation).
 */
export type CoverDto = "bare" | "grass" | "scrub" | "forest" | "marsh" | "rock" | "ice";
