// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which edge of a square a segment lies on.
 */
export type EdgeAxisDto = "horizontal" | "vertical";
