// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeDto } from "./EdgeDto";
import type { SqDto } from "./SqDto";

/**
 * A run of enterable squares along one map edge.
 */
export type EdgeExitDto = { 
/**
 * Which edge.
 */
edge: EdgeDto, 
/**
 * First square of the run.
 */
from: SqDto, 
/**
 * Last square of the run (inclusive).
 */
to: SqDto, };
