// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverLevelDto } from "./CoverLevelDto";
import type { EdgeAxisDto } from "./EdgeAxisDto";
import type { EdgeRoleDto } from "./EdgeRoleDto";

/**
 * Movement and sight rules of one unit edge.
 */
export type EdgeRuleDto = { 
/**
 * Square column.
 */
x: number, 
/**
 * Square row.
 */
y: number, 
/**
 * Which edge of the square.
 */
axis: EdgeAxisDto, 
/**
 * Why it is there.
 */
role: EdgeRoleDto, 
/**
 * Blocks movement across the edge.
 */
blocks_movement: boolean, 
/**
 * Blocks sight across the edge.
 */
blocks_sight: boolean, 
/**
 * Cover it grants.
 */
cover: CoverLevelDto, };
