// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a rules edge exists.
 */
export type EdgeRoleDto = "parapet" | "retaining" | "building" | "boundary" | "gate";
