// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqDto } from "./SqDto";

/**
 * Squares beside a door or gate.
 */
export type EntranceDto = { 
/**
 * Index into `walls`.
 */
wall: number, 
/**
 * Enterable squares on either side of it.
 */
squares: Array<SqDto>, };
