// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical fine terrain (`terrain/fine.bin`, 39.0625 m lattice) over the cell.
 */
export type FineHeights = { 
/**
 * Bilinear height at the cell centre, metres.
 */
centre_m: number, 
/**
 * Exact minimum of the bilinear surface over the footprint, metres.
 */
min_m: number, 
/**
 * Exact maximum of the bilinear surface over the footprint, metres.
 */
max_m: number, };
