// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical fine terrain descriptor.
 */
export type FineTerrainDto = { 
/**
 * Recipe that produced `terrain/fine.bin`.
 */
recipe_version: number, 
/**
 * Lattice spacing, metres (39.0625).
 */
spacing_m: number, };
