// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `/v1/health`.
 */
export type Health = { 
/**
 * Always `"ok"` when the service answers.
 */
status: string, 
/**
 * Cell contract version.
 */
contract_version: number, 
/**
 * Seed of the served world, decimal string.
 */
seed: string, };
