// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`PointSample`] height came from.
 */
export type HeightSource = "fine" | "cells";
