// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NpcId } from "./NpcId";
import type { RelationKind } from "./RelationKind";

/**
 * One family tie inside a household: `to` is `from`'s `kind`.
 */
export type HouseholdRelation = { 
/**
 * The person the relation belongs to.
 */
from: NpcId, 
/**
 * What `to` is to `from`.
 */
kind: RelationKind, 
/**
 * The other person.
 */
to: NpcId, };
