// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A household: its home building and index inside it.
 */
export type HouseholdId = { 
/**
 * Home building id.
 */
building: string, 
/**
 * Index among the building's households.
 */
index: number, };
