// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ideal and its alignment lean.
 */
export type Ideal = { 
/**
 * Short name.
 */
name: string, 
/**
 * The ideal in the person's words.
 */
text: string, 
/**
 * Alignment lean.
 */
alignment: string, 
/**
 * Coherence tags.
 */
tags: Array<string>, };
