// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An item and how many.
 */
export type Item = { 
/**
 * SRD item name.
 */
name: string, 
/**
 * Quantity.
 */
quantity: number, };
