// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobCategory } from "./JobCategory";

/**
 * A person's occupation.
 */
export type Job = { 
/**
 * Occupation key.
 */
key: string, 
/**
 * Display title.
 */
title: string, 
/**
 * Broad category.
 */
category: JobCategory, };
