// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One saved lake fragment inside an area.
 */
export type LakeDto = { 
/**
 * Tile-local id, 1-based.
 */
id: number, 
/**
 * Stable global basin id, decimal string.
 */
global_id: string, 
/**
 * Representative water surface, metres.
 */
surface_m: number, 
/**
 * Greatest local depth, metres.
 */
max_depth_m: number, 
/**
 * Global cell of supported surface outflow, if in this area.
 */
outlet: [number, number] | null, 
/**
 * Covered global cells `[gx, gy]`.
 */
cells: Array<[number, number]>, };
