// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lake covering this cell, when a saved lake lists it.
 */
export type LakeMembership = { 
/**
 * Tile-local lake id (`Lake::id`), unique within the area.
 */
lake_id: number, 
/**
 * Stable global basin id, decimal string.
 */
global_basin_id: string, 
/**
 * Representative water surface, metres above sea level.
 */
surface_m: number, 
/**
 * Water depth in this cell, metres: surface minus cell height, never negative.
 */
depth_m: number, 
/**
 * Greatest local depth of the lake fragment, metres.
 */
max_depth_m: number, };
