// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Land-use class of a cell (`society/landuse.bin`, logic/08 §landuse keys).
 */
export type LandUseDto = "none" | "built" | "field" | "pasture" | "orchard" | "woodland" | "mill" | "mine" | "meadow" | "fallow" | "farmstead";
