// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latitude belt the continent sits in, degrees north.
 */
export type LatitudeDto = { 
/**
 * Southern edge.
 */
south_deg: number, 
/**
 * Northern edge.
 */
north_deg: number, };
