// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverDto } from "./CoverDto";
import type { LandUseDto } from "./LandUseDto";
import type { RoadDto } from "./RoadDto";
import type { TerrainKindDto } from "./TerrainKindDto";

/**
 * Enum codes: a column value `i` means the `i`-th entry.
 */
export type Legend = { 
/**
 * Codes of the `terrain` column.
 */
terrain: Array<TerrainKindDto>, 
/**
 * Codes of the `cover` column.
 */
cover: Array<CoverDto>, 
/**
 * Codes of the `road` column.
 */
road: Array<RoadDto>, 
/**
 * Codes of the `land_use` column (0 also when the world has no `society/`).
 */
land_use: Array<LandUseDto>, };
