// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One placeable asset.
 */
export type LibraryAssetDto = { 
/**
 * Asset id for `AssetRef::Id`.
 */
id: string, 
/**
 * `prop` or `vegetation`.
 */
class: string, 
/**
 * Draw layer (`floor`, `prop`, `canopy`, …).
 */
layer: string, 
/**
 * Footprint in squares, `[w, h]`.
 */
footprint: [number, number], 
/**
 * Allowed rotations in degrees.
 */
rotations: Array<number>, 
/**
 * Tags as `key:value` strings for tag queries (I8), sorted.
 */
tags: Array<string>, 
/**
 * SRD cover it grants.
 */
cover: string, 
/**
 * Blocks sight.
 */
blocks_sight: boolean, 
/**
 * Blocks movement.
 */
blocks_movement: boolean, 
/**
 * Makes its squares difficult terrain.
 */
difficult_terrain: boolean, };
