// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SRD 5.1 lifestyle.
 */
export type Lifestyle = "wretched" | "squalid" | "poor" | "modest" | "comfortable" | "wealthy" | "aristocratic";
