// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A light source not attached to an asset.
 */
export type LightSourceDto = { 
/**
 * Position in squares.
 */
x: number, 
/**
 * Position in squares.
 */
y: number, 
/**
 * Bright-light radius in feet.
 */
radius_ft: number, 
/**
 * RGB colour.
 */
colour: [number, number, number], };
