// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a creature moves through a square (SRD 5.1 "Movement").
 */
export type MovementDto = "normal" | "difficult" | "wade" | "swim" | "impassable";
