// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person's name.
 */
export type Name = { 
/**
 * Given name.
 */
given: string, 
/**
 * Family name.
 */
family: string, 
/**
 * Optional nickname or epithet.
 */
byname: string | null, };
