// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorBody } from "./ApiErrorBody";

/**
 * The 501 body of a feature whose source crate does not exist yet.
 */
export type NotYetError = { 
/**
 * The error details; `code` is `not_implemented`.
 */
error: ApiErrorBody, 
/**
 * Crate planned to provide the feature, for example `arda-refine`.
 */
planned_source: string, };
