// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HouseholdId } from "./HouseholdId";
import type { Job } from "./Job";
import type { Lifestyle } from "./Lifestyle";
import type { Name } from "./Name";
import type { NpcId } from "./NpcId";
import type { Personality } from "./Personality";
import type { Relationship } from "./Relationship";
import type { Sex } from "./Sex";
import type { Sheet } from "./Sheet";
import type { SocialRank } from "./SocialRank";

/**
 * One inhabitant with a full SRD 5.1 sheet (`logic/13` §npc-game-schema).
 */
export type Npc = { 
/**
 * Stable id.
 */
id: NpcId, 
/**
 * Name.
 */
name: Name, 
/**
 * SRD race key.
 */
ancestry: string, 
/**
 * SRD race display name.
 */
ancestry_name: string, 
/**
 * SRD subrace.
 */
subrace: string | null, 
/**
 * Age in years.
 */
age: number, 
/**
 * Sex.
 */
sex: Sex, 
/**
 * Occupation.
 */
job: Job, 
/**
 * Workplace building id.
 */
workplace_building: string | null, 
/**
 * Home building id.
 */
home_building: string, 
/**
 * Household.
 */
household: HouseholdId, 
/**
 * Master of the workplace, for employees.
 */
employer: NpcId | null, 
/**
 * Social standing.
 */
social_rank: SocialRank, 
/**
 * Wealth, 0–255.
 */
wealth: number, 
/**
 * SRD lifestyle.
 */
lifestyle: Lifestyle, 
/**
 * Personality.
 */
personality: Personality, 
/**
 * Ties, sorted.
 */
relationships: Array<Relationship>, 
/**
 * SRD 5.1 character sheet.
 */
sheet: Sheet, 
/**
 * Whether the person is a stored notable.
 */
notable: boolean, };
