// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingSpec } from "./BuildingSpec";
import type { Population } from "./Population";
import type { SettlementProfile } from "./SettlementProfile";

/**
 * Body of `GET /v1/npc/demo`: the market-town example and its population.
 */
export type NpcDemo = { 
/**
 * World seed as a decimal string.
 */
world_seed: string, 
/**
 * The example settlement.
 */
settlement: SettlementProfile, 
/**
 * Its buildings.
 */
buildings: Array<BuildingSpec>, 
/**
 * Its population.
 */
population: Population, };
