// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Npc } from "./Npc";

/**
 * One person of a query page.
 */
export type NpcEntry = { 
/**
 * `"<settlement>.<building>.<index>"`: resolves with `GET /v1/npc/{ref}`,
 * commoners included.
 */
npc_ref: string, 
/**
 * The settlement, a decimal string.
 */
settlement_id: string, 
/**
 * Whether the person is a stored notable.
 */
notable: boolean, 
/**
 * The person with their SRD 5.1 sheet.
 */
npc: Npc, };
