// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An inhabitant's id: the `arda-ids` u64 as a decimal string.
 */
export type NpcId = string;
