// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NpcEntry } from "./NpcEntry";

/**
 * A page of people (TS `NpcPage`).
 */
export type NpcPage = { 
/**
 * [`NPC_PAGE_FORMAT`].
 */
format_version: number, 
/**
 * The matches, in settlement-id then skeleton order (home building id,
 * then resident index).
 */
npcs: Array<NpcEntry>, 
/**
 * Pass as `?cursor=` for the next page; `null` on the last one.
 */
next_cursor: string | null, 
/**
 * Settlements whose skeletons this page scanned (bounded per page).
 */
scanned_settlements: number, };
