// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SRD 5.1 vision obscurement of a square.
 */
export type ObscurementDto = "clear" | "light" | "heavy";
