// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ideal } from "./Ideal";

/**
 * Personality.
 */
export type Personality = { 
/**
 * Two traits.
 */
traits: Array<string>, 
/**
 * One ideal.
 */
ideal: Ideal, 
/**
 * One bond.
 */
bond: string, 
/**
 * One flaw.
 */
flaw: string, 
/**
 * A voice or mannerism hook.
 */
mannerism: string, 
/**
 * One-line summary.
 */
summary: string, };
