// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRefDto } from "./AssetRefDto";

/**
 * A prop or vegetation placement.
 */
export type PlacementDto = { 
/**
 * What to place.
 */
asset: AssetRefDto, 
/**
 * Anchor position in squares (`3.5` is a square centre).
 */
x: number, 
/**
 * Anchor position in squares.
 */
y: number, 
/**
 * Clockwise rotation in degrees.
 */
rotation: number, 
/**
 * Horizontal mirror, applied before rotation.
 */
mirror: boolean, };
