// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellSample } from "./CellSample";
import type { HeightSource } from "./HeightSource";

/**
 * A height query at arbitrary world metres, plus the nearest cell's sample.
 */
export type PointSample = { 
/**
 * [`CONTRACT_VERSION`].
 */
contract_version: number, 
/**
 * Query position east of the world origin, metres.
 */
x_m: number, 
/**
 * Query position south of the world origin, metres.
 */
y_m: number, 
/**
 * Interpolated elevation, metres.
 */
height_m: number, 
/**
 * Which surface was interpolated.
 */
height_source: HeightSource, 
/**
 * Sample of the cell containing the point.
 */
cell: CellSample, };
