// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingSpec } from "./BuildingSpec";
import type { SettlementProfile } from "./SettlementProfile";

/**
 * Body of `POST /v1/npc/population`.
 */
export type PopulationRequest = { 
/**
 * World seed as a decimal string.
 */
world_seed: string, 
/**
 * The settlement to populate.
 */
settlement: SettlementProfile, 
/**
 * Its buildings.
 */
buildings: Array<BuildingSpec>, };
