// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Household } from "./Household";
import type { JobCategory } from "./JobCategory";
import type { Npc } from "./Npc";
import type { RosterEntry } from "./RosterEntry";

/**
 * The population of one settlement; notables stored in full.
 */
export type Population = { 
/**
 * Settlement id.
 */
settlement_id: string, 
/**
 * Total inhabitants.
 */
population: number, 
/**
 * Every household.
 */
households: Array<Household>, 
/**
 * Stored notables.
 */
npcs: Array<Npc>, 
/**
 * Inhabitants who are not stored.
 */
commoner_count: number, 
/**
 * Job keys referenced by the roster.
 */
job_keys: Array<string>, 
/**
 * Category of each job key.
 */
job_categories: Array<JobCategory>, 
/**
 * One entry per inhabitant, in id order.
 */
roster: Array<RosterEntry>, };
