// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one neighbour.
 */
export type PrefetchStatus = "queued" | "pending" | "dropped";
