// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrefetchStatus } from "./PrefetchStatus";

/**
 * One neighbour of a prefetch.
 */
export type PrefetchCell = { 
/**
 * Cell column.
 */
gx: number, 
/**
 * Cell row.
 */
gy: number, 
/**
 * Queue outcome.
 */
status: PrefetchStatus, 
/**
 * Whether its image pyramid warms too (else JSON and blocks only).
 */
image: boolean, };
