// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/tactical/prefetch` (TS `PrefetchRequest`).
 */
export type PrefetchRequest = { 
/**
 * Centre cell column.
 */
gx: number, 
/**
 * Centre cell row.
 */
gy: number, 
/**
 * Rings of neighbours to warm, 1–2 (default 1: the 8 neighbours).
 */
radius?: number, 
/**
 * Pixels per square of the images to warm (the cell route's options;
 * default 128).
 */
ppsq?: number, 
/**
 * Warm the demo-overlay blocks instead (`?demo_overlays=1`).
 */
demo_overlays?: boolean, };
