// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrefetchCell } from "./PrefetchCell";

/**
 * `202` body of `POST /v1/tactical/prefetch` (TS `PrefetchAccepted`).
 */
export type PrefetchAccepted = { 
/**
 * The radius used.
 */
radius: number, 
/**
 * The ppsq warmed.
 */
ppsq: number, 
/**
 * The neighbours inside the world, nearest ring first, row-major.
 */
cells: Array<PrefetchCell>, 
/**
 * Cells waiting after this request.
 */
queue_len: number, };
