// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionKindDto } from "./RegionKindDto";

/**
 * Merged squares of one kind as closed rings on grid vertices (even-odd fill).
 */
export type RegionDto = { 
/**
 * What the region marks.
 */
kind: RegionKindDto, 
/**
 * Closed rings of `[x, y]` vertices (first point not repeated).
 */
rings: Array<Array<[number, number]>>, };
