// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How two people are related.
 */
export type RelationKind = "spouse" | "parent" | "child" | "sibling" | "landlord" | "lodger" | "employer" | "employee" | "friend" | "rival";
