// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NpcId } from "./NpcId";
import type { RelationKind } from "./RelationKind";

/**
 * One relationship: `other` is this person's `kind`.
 */
export type Relationship = { 
/**
 * What the other person is to this one.
 */
kind: RelationKind, 
/**
 * The other person.
 */
other: NpcId, };
