// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The watercourse reach that owns this cell, when a saved river course passes through it.
 */
export type RiverMembership = { 
/**
 * Tile-local segment id (`RiverSegment::id`), unique within the area.
 */
segment_id: number, 
/**
 * Stable global reach id, decimal string (u64 does not fit a JS number).
 */
global_reach_id: string, 
/**
 * Strahler order of the segment.
 */
order: number, 
/**
 * Segment channel width, metres.
 */
width_m: number, 
/**
 * Segment mean discharge, m³/s.
 */
discharge_m3s: number, };
