// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminusDto } from "./TerminusDto";

/**
 * One saved watercourse reach fragment inside an area.
 */
export type RiverDto = { 
/**
 * Tile-local id, 1-based.
 */
id: number, 
/**
 * Stable global reach id, decimal string.
 */
global_id: string, 
/**
 * Strahler order.
 */
order: number, 
/**
 * Channel width, metres.
 */
width_m: number, 
/**
 * Mean discharge, m³/s.
 */
discharge_m3s: number, 
/**
 * Local downstream segment at a confluence, if any.
 */
feeds: number | null, 
/**
 * How the segment ends.
 */
ends: TerminusDto, 
/**
 * Global cells `[gx, gy]`, upstream to downstream.
 */
course: Array<[number, number]>, };
