// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Road class crossing the cell (source: `Cell::road`).
 */
export type RoadDto = "none" | "track" | "road" | "highway";
