// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NpcId } from "./NpcId";

/**
 * Compact index entry for one inhabitant.
 */
export type RosterEntry = { 
/**
 * Person.
 */
id: NpcId, 
/**
 * Index into `Population.job_keys`.
 */
job: number, 
/**
 * Workplace building id.
 */
workplace: string | null, 
/**
 * Whether the person is a stored notable.
 */
notable: boolean, };
