// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverLevelDto } from "./CoverLevelDto";

/**
 * One square's rules; an absent field means "no opinion".
 */
export type RulesCellDto = { 
/**
 * Difficult terrain.
 */
difficult?: boolean, 
/**
 * Water depth in feet: under 5 wades, 5 or more swims (I15).
 */
water_depth_ft?: number, 
/**
 * Cover the square's contents grant.
 */
cover?: CoverLevelDto, 
/**
 * Heavily obscured.
 */
blocks_sight?: boolean, 
/**
 * Lightly obscured.
 */
lightly_obscured?: boolean, 
/**
 * Impassable.
 */
blocks_movement?: boolean, 
/**
 * A walkable deck (bridge, jetty) over the square.
 */
deck?: boolean, 
/**
 * Layer extras: `feature`, `road_class`, `deck_elevation_ft` (ways),
 * `crop`, `field`, `furrow` (fields), `building` (town).
 */
ext?: Record<string, unknown>, };
