// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeRuleDto } from "./EdgeRuleDto";
import type { RulesCellDto } from "./RulesCellDto";

/**
 * The per-square rules sidecar, format 2.
 */
export type RulesSidecarDto = { 
/**
 * Always 2.
 */
format_version: number, 
/**
 * Width in squares (the layout's).
 */
width: number, 
/**
 * Height in squares.
 */
height: number, 
/**
 * Row-major cells.
 */
squares: Array<RulesCellDto>, 
/**
 * Low edge features that are not wall-kit walls (always present on
 * the wire; the domain JSON omits an empty list).
 */
edges: Array<EdgeRuleDto>, };
