// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row-major per-square layer as runs `[[count, value], …]`, expanding to
 * `width × height` values (`arda_scene::Grid`).
 */
export type Runs<T> = Array<[number, T]>;
