// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

/**
 * A saving throw.
 */
export type SaveBonus = { 
/**
 * Ability.
 */
ability: Ability, 
/**
 * Total bonus.
 */
bonus: number, 
/**
 * Whether proficiency applies.
 */
proficient: boolean, };
