// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverLevelDto } from "./CoverLevelDto";
import type { MovementDto } from "./MovementDto";
import type { ObscurementDto } from "./ObscurementDto";
import type { RegionDto } from "./RegionDto";
import type { Runs } from "./Runs";
import type { SceneLightDto } from "./SceneLightDto";
import type { SceneWallDto } from "./SceneWallDto";
import type { SpawnHintsDto } from "./SpawnHintsDto";
import type { TokenSlotDto } from "./TokenSlotDto";
import type { VisionBlockerDto } from "./VisionBlockerDto";

/**
 * `arda-scene` `Scene` format 1: everything the game needs to run a map.
 */
export type SceneDto = { 
/**
 * Schema version (1).
 */
format_version: number, 
/**
 * Layout name.
 */
name: string, 
/**
 * Width in squares.
 */
width: number, 
/**
 * Height in squares.
 */
height: number, 
/**
 * Seed the asset queries were resolved with, a decimal string.
 */
seed: string, 
/**
 * Library name.
 */
library: string, 
/**
 * Library art version.
 */
library_version: string, 
/**
 * Per-square movement.
 */
movement: Runs<MovementDto>, 
/**
 * Per-square climb mask: bit `d` (0 N, 1 NE, … 7 NW) set means the step
 * to that neighbour crosses 10 ft or more and needs climbing.
 */
climb: Runs<number>, 
/**
 * Per-square cover granted by what stands in the square.
 */
cover: Runs<CoverLevelDto>, 
/**
 * Per-square obscurement.
 */
obscured: Runs<ObscurementDto>, 
/**
 * Per-square elevation in feet.
 */
elevation_ft: Runs<number>, 
/**
 * Per-square water depth in feet.
 */
water_depth_ft: Runs<number>, 
/**
 * Wall, door, window, gate and secret-door polylines.
 */
walls: Array<SceneWallDto>, 
/**
 * Canopy and prop polygons that obscure vision.
 */
vision_blockers: Array<VisionBlockerDto>, 
/**
 * Light sources.
 */
lights: Array<SceneLightDto>, 
/**
 * Difficult-terrain and water regions.
 */
regions: Array<RegionDto>, 
/**
 * Token placement hints.
 */
spawn_hints: SpawnHintsDto, 
/**
 * NPC token slots.
 */
tokens: Array<TokenSlotDto>, 
/**
 * World square of square `(0, 0)` (I17): present in
 * `TacticalBlockDto.scene`, absent in `TacticalScene.scene`, whose
 * envelope carries it.
 */
origin_gs?: [number, number], };
