// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A light source with SRD bright and dim radii.
 */
export type SceneLightDto = { 
/**
 * Position in squares.
 */
x: number, 
/**
 * Position in squares.
 */
y: number, 
/**
 * Bright-light radius in feet.
 */
bright_ft: number, 
/**
 * Outer edge of dim light in feet.
 */
dim_ft: number, 
/**
 * RGB colour.
 */
colour: [number, number, number], 
/**
 * Emitting asset id; absent for a free layout light.
 */
asset?: string, };
