// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverLevelDto } from "./CoverLevelDto";
import type { WallKindDto } from "./WallKindDto";

/**
 * A wall polyline on grid vertices.
 */
export type SceneWallDto = { 
/**
 * Feature type.
 */
kind: WallKindDto, 
/**
 * Open state of doors, gates and secret doors; absent otherwise.
 */
open?: boolean, 
/**
 * Grid vertices `[x, y]`, at least two.
 */
points: Array<[number, number]>, 
/**
 * Blocks line of sight in its current state.
 */
blocks_sight: boolean, 
/**
 * Blocks movement in its current state.
 */
blocks_movement: boolean, 
/**
 * Blocks light in its current state.
 */
blocks_light: boolean, 
/**
 * Cover it grants when it does not block sight.
 */
cover: CoverLevelDto, 
/**
 * Wall kit name.
 */
kit: string, };
