// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time of day a scene's tokens are placed for.
 */
export type SceneTime = "day" | "night";
