// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a settlement lives on.
 */
export type SettlementFunction = "farming" | "pastoral" | "fishing" | "port" | "market" | "mining" | "logging" | "crafting" | "fortress" | "abbey" | "crossing" | "capital";
