// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Biome } from "./Biome";
import type { SettlementFunction } from "./SettlementFunction";
import type { Tier } from "./Tier";
import type { Tongue } from "./Tongue";

/**
 * One settlement to populate.
 */
export type SettlementProfile = { 
/**
 * Settlement id.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Size class.
 */
tier: Tier, 
/**
 * Number of inhabitants.
 */
population: number, 
/**
 * Economic functions.
 */
functions: Array<SettlementFunction>, 
/**
 * Wealth, 0–255.
 */
wealth: number, 
/**
 * Culture key.
 */
culture: string, 
/**
 * Realm id.
 */
realm_id: string, 
/**
 * Biome.
 */
biome: Biome, 
/**
 * On a sea coast.
 */
coastal: boolean, 
/**
 * On a river.
 */
riverine: boolean, 
/**
 * Optional ancestry weights replacing the culture's table.
 */
ancestry_mix?: { [key in string]: number } | null, 
/**
 * The local speech the settlement was named in (`arda_names::Tongue`).
 */
tongue?: Tongue, };
