// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attack } from "./Attack";
import type { Coins } from "./Coins";
import type { Item } from "./Item";
import type { SaveBonus } from "./SaveBonus";
import type { SheetKind } from "./SheetKind";
import type { SkillBonus } from "./SkillBonus";
import type { Spellcasting } from "./Spellcasting";

/**
 * A full SRD 5.1 sheet.
 */
export type Sheet = { 
/**
 * Stat block or class build.
 */
kind: SheetKind, 
/**
 * Size category.
 */
size: string, 
/**
 * STR, DEX, CON, INT, WIS, CHA.
 */
abilities: [number, number, number, number, number, number], 
/**
 * Their modifiers.
 */
modifiers: [number, number, number, number, number, number], 
/**
 * Proficiency bonus.
 */
proficiency_bonus: number, 
/**
 * All six saving throws.
 */
saves: Array<SaveBonus>, 
/**
 * Proficient skills.
 */
skills: Array<SkillBonus>, 
/**
 * Hit points.
 */
hit_points: number, 
/**
 * Hit dice.
 */
hit_dice: string, 
/**
 * Armour class.
 */
armor_class: number, 
/**
 * Worn armour and shield.
 */
armor: Array<string>, 
/**
 * Walking speed, feet.
 */
speed: number, 
/**
 * Senses.
 */
senses: Array<string>, 
/**
 * Passive Wisdom (Perception).
 */
passive_perception: number, 
/**
 * Languages.
 */
languages: Array<string>, 
/**
 * Damage resistances.
 */
damage_resistances: Array<string>, 
/**
 * Attacks.
 */
attacks: Array<Attack>, 
/**
 * Features by name.
 */
features: Array<string>, 
/**
 * Equipment.
 */
equipment: Array<Item>, 
/**
 * Coins.
 */
coins: Coins, 
/**
 * Spellcasting, for casters.
 */
spellcasting: Spellcasting | null, };
