// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Background } from "./Background";

/**
 * What the sheet is built from.
 */
export type SheetKind = { "type": "stat_block", 
/**
 * Stat block name.
 */
name: string, 
/**
 * Challenge rating.
 */
challenge_rating: string, 
/**
 * Experience points.
 */
xp: number, } | { "type": "class", 
/**
 * Class name.
 */
class: string, 
/**
 * SRD subclass.
 */
subclass: string | null, 
/**
 * Class level.
 */
level: number, 
/**
 * Flavour background.
 */
background: Background, };
