// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Continent extent in kilometres (manifest `config.size_km`).
 */
export type SizeKmDto = { 
/**
 * East–west extent.
 */
width: number, 
/**
 * North–south extent.
 */
height: number, };
