// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

/**
 * A proficient skill.
 */
export type SkillBonus = { 
/**
 * SRD skill name.
 */
name: string, 
/**
 * Ability used.
 */
ability: Ability, 
/**
 * Total bonus.
 */
bonus: number, 
/**
 * Whether proficiency is doubled.
 */
expertise: boolean, };
