// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Derived snow proxy. Not simulated: a documented rule of thumb on saved climate.
 */
export type SnowSample = { 
/**
 * Perennial snow cover of the cell, 0–1 (see [`snow`]).
 */
fraction: number, 
/**
 * The same rule at the footprint's highest fine-terrain point; `null` without fine terrain.
 */
peak_fraction: number | null, 
/**
 * `fraction >= 0.5`, or permanent-ice cover.
 */
perennial: boolean, 
/**
 * Altitude, metres, where the lapse-adjusted mean annual temperature crosses
 * the snow midpoint (−5.5 °C). Ground above it is snowy under this proxy.
 */
snowline_m: number, };
