// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standing in local society.
 */
export type SocialRank = "dependent" | "labourer" | "tradesfolk" | "master" | "gentry" | "noble";
