// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeExitDto } from "./EdgeExitDto";
import type { EntranceDto } from "./EntranceDto";
import type { SqDto } from "./SqDto";

/**
 * Where tokens may be put.
 */
export type SpawnHintsDto = { 
/**
 * Open normal-movement squares, row-major.
 */
open: Array<SqDto>, 
/**
 * Squares by doors and gates.
 */
entrances: Array<EntranceDto>, 
/**
 * Enterable runs along the map edges, N, E, S, W order.
 */
exits: Array<EdgeExitDto>, };
