// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { SpellRef } from "./SpellRef";

/**
 * Spellcasting block.
 */
export type Spellcasting = { 
/**
 * Casting ability.
 */
ability: Ability, 
/**
 * Spell save DC.
 */
save_dc: number, 
/**
 * Spell attack bonus.
 */
attack_bonus: number, 
/**
 * Slots per spell level (index 0 = 1st level).
 */
slots: Array<number>, 
/**
 * Pact Magic slots.
 */
pact_magic: boolean, 
/**
 * Cantrips and spells.
 */
spells: Array<SpellRef>, };
