// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A spell known or prepared.
 */
export type SpellRef = { 
/**
 * SRD spell name.
 */
name: string, 
/**
 * Spell level, 0 for cantrips.
 */
level: number, };
