// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A square `[x, y]` (column, row) in the scene's own squares.
 */
export type SqDto = [number, number];
