// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One 5-ft square.
 */
export type SquareDto = { 
/**
 * Ground type key, matching a texture's `ground` field.
 */
ground: string, 
/**
 * Elevation in feet.
 */
elevation_ft: number, 
/**
 * Water depth in feet; zero is dry land.
 */
water_depth_ft: number, 
/**
 * Climate dryness, `0` (lush) to `255` (parched steppe); omitted when
 * zero. The compositor tints vegetated ground toward dry grass by it.
 */
dryness?: number, };
