// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tile pyramid geometry of one render.
 */
export type TacticalTilesDto = { 
/**
 * Tile edge in pixels (512).
 */
tile_px: number, 
/**
 * Output pixels per square of the render the pyramid is cut from.
 */
ppsq: number, 
/**
 * Full-resolution render width, pixels.
 */
image_width_px: number, 
/**
 * Full-resolution render height, pixels.
 */
image_height_px: number, 
/**
 * Deepest zoom; it is the render at full resolution.
 */
max_zoom: number, 
/**
 * Tile file extension: `webp`.
 */
format: string, };
