// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TacticalTilesDto } from "./TacticalTilesDto";

/**
 * One built-in layout.
 */
export type TacticalLayoutSummary = { 
/**
 * Name used in `/v1/tactical/layout/{name}`.
 */
name: string, 
/**
 * Width in 5-ft squares.
 */
width: number, 
/**
 * Height in 5-ft squares.
 */
height: number, 
/**
 * Tile pyramid geometry at the default ppsq.
 */
tiles: TacticalTilesDto, };
