// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TacticalLayoutSummary } from "./TacticalLayoutSummary";

/**
 * `GET /v1/tactical/layouts`: the built-in test layouts.
 */
export type TacticalLayouts = { 
/**
 * Seed of the served world (a decimal string); part of every render seed and cache key.
 */
world_seed: string, 
/**
 * `library_version` of the loaded catalogue; part of every render cache key.
 */
library_version: string, 
/**
 * Output pixels per square clients may request.
 */
ppsq_options: Array<number>, 
/**
 * Default output pixels per square.
 */
default_ppsq: number, 
/**
 * Layouts in name order.
 */
layouts: Array<TacticalLayoutSummary>, };
