// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroundKeyDto } from "./GroundKeyDto";
import type { LibraryAssetDto } from "./LibraryAssetDto";
import type { WallKitDto } from "./WallKitDto";

/**
 * The loaded asset library, summarised.
 */
export type TacticalLibraryDto = { 
/**
 * Library name.
 */
library: string, 
/**
 * `library_version`; part of every render cache key.
 */
library_version: string, 
/**
 * Art resolution in pixels per square.
 */
pixels_per_square: number, 
/**
 * Ground keys a `Square.ground` may use, sorted.
 */
grounds: Array<GroundKeyDto>, 
/**
 * Wall kits a `WallSegment.kit` may use, sorted.
 */
wall_kits: Array<WallKitDto>, 
/**
 * Placeable assets (props and vegetation), sorted by id.
 */
assets: Array<LibraryAssetDto>, };
