// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightSourceDto } from "./LightSourceDto";
import type { PlacementDto } from "./PlacementDto";
import type { SquareDto } from "./SquareDto";
import type { WallSegmentDto } from "./WallSegmentDto";

/**
 * Mirror of `arda_tactical::TacticalLayout`: a W × H battle map.
 */
export type TacticalLayoutDto = { 
/**
 * Layout name.
 */
name: string, 
/**
 * Width in squares.
 */
width: number, 
/**
 * Height in squares.
 */
height: number, 
/**
 * Row-major squares, `width × height` of them.
 */
squares: Array<SquareDto>, 
/**
 * Wall, door, window and gate segments on square edges.
 */
walls: Array<WallSegmentDto>, 
/**
 * Props and vegetation.
 */
placements: Array<PlacementDto>, 
/**
 * Free-standing light sources.
 */
lights: Array<LightSourceDto>, 
/**
 * World square of square `(0, 0)` (I10); absent for layouts with no
 * world position.
 */
origin?: [number, number], };
