// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RulesSidecarDto } from "./RulesSidecarDto";
import type { TacticalLayoutDto } from "./TacticalLayoutDto";
import type { TacticalTilesDto } from "./TacticalTilesDto";

/**
 * `GET /v1/tactical/cell/{gx}/{gy}` and `GET /v1/tactical/window`: one
 * world-derived block or window (logic/16 §api-tactical).
 */
export type TacticalBlockDto = { 
/**
 * Envelope version of this body ([`TACTICAL_FORMAT`]).
 */
tactical_format: number, 
/**
 * `TacticalLayout` schema version ([`LAYOUT_SCHEMA`]).
 */
layout_schema: number, 
/**
 * Top-left square in world squares (64 per cell); equals `layout.origin`.
 */
origin: [number, number], 
/**
 * Width and height in squares.
 */
size: [number, number], 
/**
 * Compositor seed of the images (a decimal string); the scene resolves
 * asset queries with the same seed.
 */
render_seed: string, 
/**
 * What the compositor draws.
 */
layout: TacticalLayoutDto, 
/**
 * Per-square rules, `arda-scene` `RulesSidecar` format 2, or `null`.
 */
rules: RulesSidecarDto | null, 
/**
 * Provenance: `source`, `relaxed`, `overlays`, `demo_at`, ….
 */
meta: { [key in string]: string }, 
/**
 * Scene data from the same layout (`arda-scene` `Scene`, format 1:
 * movement, climb, cover, obscurement, walls, lights, regions, spawn
 * hints), or `null` when not requested.
 */
scene: unknown, 
/**
 * Tile pyramid geometry at the requested ppsq.
 */
tiles: TacticalTilesDto, };
