// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDto } from "./SceneDto";
import type { SceneTime } from "./SceneTime";
import type { Token } from "./Token";

/**
 * `GET /v1/tactical/cell/{gx}/{gy}/scene`: the scene of one block and the
 * NPCs on it.
 */
export type TacticalScene = { 
/**
 * Envelope version ([`SCENE_FORMAT`]).
 */
tactical_format: number, 
/**
 * World square of the block's top-left square.
 */
origin_gs: [number, number], 
/**
 * `day` or `night`.
 */
time: SceneTime, 
/**
 * The `arda-scene` scene (format 1), described by [`SceneDto`].
 */
scene: SceneDto, 
/**
 * NPC tokens.
 */
tokens: Array<Token>, };
