// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a river segment ends.
 */
export type TerminusDto = "junction" | "sea" | "lake" | "off_tile" | "basin" | "divergence";
