// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sea, dry land, or lake surface (source: `Cell::terrain`).
 */
export type TerrainKindDto = "sea" | "land" | "lake";
