// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settlement size class.
 */
export type Tier = "hamlet" | "village" | "town" | "city";
