// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slippy overview tile pyramid geometry.
 */
export type TilePyramidDto = { 
/**
 * Tile edge, pixels.
 */
tile_px: number, 
/**
 * Deepest zoom; zoom 0 is the whole world in one tile.
 */
max_zoom: number, 
/**
 * Edge of the square pyramid at `max_zoom`, pixels (`tile_px << max_zoom`).
 */
base_px: number, 
/**
 * Overview image width inside the base square, pixels.
 */
image_width_px: number, 
/**
 * Overview image height inside the base square, pixels.
 */
image_height_px: number, 
/**
 * Deepest zoom of `/v1/tiles/relief` (levels `max_zoom + 1..=` this);
 * equal to `max_zoom` when the world has no relief levels.
 */
relief_max_zoom: number, };
