// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenKind } from "./TokenKind";

/**
 * One token on the scene.
 */
export type Token = { 
/**
 * The NPC, a decimal string (resolve it with `GET /v1/npc/{id}`).
 */
npc_id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Square column within the block.
 */
x: number, 
/**
 * Square row within the block.
 */
y: number, 
/**
 * The building it stands in, a decimal string.
 */
building_id: string, 
/**
 * Its settlement, a decimal string.
 */
settlement_id: string, 
/**
 * `worker` (at its workplace) or `resident` (at home).
 */
kind: TokenKind, };
