// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a token stands where it does.
 */
export type TokenKind = "worker" | "resident";
