// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an NPC's token stands (scene token slot).
 */
export type TokenSlotDto = { 
/**
 * NPC id, a decimal string.
 */
npc_id: string, 
/**
 * Token centre in squares (`3.5` is a square centre).
 */
x: number, 
/**
 * Token centre in squares.
 */
y: number, 
/**
 * Facing in degrees clockwise from north, `0..360`.
 */
facing: number, };
