// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recipe of a place's local speech (`arda_names::Tongue`): seeds are
 * decimal strings.
 */
export type Tongue = { 
/**
 * Culture preset key (`heartland`, `sylvan`, …).
 */
preset: string, 
/**
 * Seed of the standard language.
 */
language_seed: string, 
/**
 * Seed of the shared substrate tongue.
 */
substrate_seed: string, 
/**
 * Seed of the region's dialect map.
 */
dialect_seed: string, 
/**
 * Dialect map width, cells.
 */
width: number, 
/**
 * Dialect map height, cells.
 */
height: number, 
/**
 * Place column, cells.
 */
x: number, 
/**
 * Place row, cells.
 */
y: number, };
