// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockerKindDto } from "./BlockerKindDto";
import type { ObscurementDto } from "./ObscurementDto";

/**
 * A polygon that obscures vision.
 */
export type VisionBlockerDto = { 
/**
 * Source class.
 */
kind: BlockerKindDto, 
/**
 * Asset id.
 */
asset: string, 
/**
 * `light` for foliage, `heavy` for opaque.
 */
obscurement: ObscurementDto, 
/**
 * Closed polygon in squares, clockwise in y-down coordinates.
 */
polygon: Array<[number, number]>, };
