// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeAxisDto } from "./EdgeAxisDto";
import type { WallRoleDto } from "./WallRoleDto";

/**
 * A wall-kit edge feature.
 */
export type WallSegmentDto = { 
/**
 * Square column.
 */
x: number, 
/**
 * Square row.
 */
y: number, 
/**
 * Which edge.
 */
axis: EdgeAxisDto, 
/**
 * Edge role.
 */
kind: WallRoleDto, 
/**
 * Wall kit name.
 */
kit: string, 
/**
 * Free edge tags: `locked` and `secret` on doors. Absent when empty.
 */
tags?: Array<string>, };
