// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wall-kit piece roles; layouts use the edge roles `run`, `door`, `window`, `gate`.
 */
export type WallRoleDto = "run" | "door" | "window" | "gate" | "corner" | "tee" | "cross" | "end" | "post";
