// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One wall kit and the roles it has pieces for.
 */
export type WallKitDto = { 
/**
 * Kit name, e.g. `stone`.
 */
kit: string, 
/**
 * Piece roles (`run`, `door`, `window`, `gate`, joints), sorted.
 */
roles: Array<string>, };
