// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FineTerrainDto } from "./FineTerrainDto";
import type { LatitudeDto } from "./LatitudeDto";
import type { SizeKmDto } from "./SizeKmDto";
import type { TilePyramidDto } from "./TilePyramidDto";

/**
 * `/v1/world`: identity, size and grids of the served world.
 */
export type WorldInfo = { 
/**
 * Cell contract version.
 */
contract_version: number, 
/**
 * HTTP API version.
 */
api_version: string, 
/**
 * World seed as a decimal string (u64 does not fit a JS number).
 */
seed: string, 
/**
 * Generator version that wrote the world.
 */
arda_version: string, 
/**
 * Stored format major.
 */
format_version: number, 
/**
 * Nominal continent extent.
 */
size_km: SizeKmDto, 
/**
 * Latitude belt.
 */
latitude: LatitudeDto, 
/**
 * Area tiles per row.
 */
areas_wide: number, 
/**
 * Area tile rows.
 */
areas_high: number, 
/**
 * Cells along an area edge (512).
 */
area_cells: number, 
/**
 * Cell spacing, metres (100).
 */
cell_size_m: number, 
/**
 * Global cell columns (`areas_wide × 512`).
 */
cells_wide: number, 
/**
 * Global cell rows (`areas_high × 512`).
 */
cells_high: number, 
/**
 * Fine terrain, when the world has it.
 */
fine_terrain: FineTerrainDto | null, 
/**
 * Overview tile pyramid.
 */
tiles: TilePyramidDto, };
