//! The population skeleton: who lives where, in which household, with which
//! job and which friends. It is cheap (a few integers per person) and fully
//! determined by the inputs, so any single person can be regenerated by
//! rebuilding it and expanding just that person (`person.rs`).
//!
//! Build order (each step depends only on the previous ones and on seed keys,
//! never on input order):
//! 1. sort buildings by id and share the population out by capacity;
//! 2. households per building from the building's own key (`households.rs`);
//! 3. jobs: residents staff their own workplace, then the pool fills the
//!    remaining slots, society offices bind (`slots.rs`), officials not
//!    covered by an office are appointed up to the tier's civic cap,
//!    everyone else takes a land job, and notables are settled to the
//!    tier's range (`jobs.rs`);
//! 4. friend and rival pairs (`social.rs`).

mod households;
mod jobs;
mod person;
mod slots;
mod social;

use crate::data::content::{Culture, TierData, WorkplaceData};
use crate::data::srd::RaceData;
use crate::data::Data;
use crate::error::NpcError;
use crate::input::{
    BuildingFunction, BuildingId, BuildingSpec, Craft, NotableSlot, SettlementProfile,
};
use crate::names::Tongues;
use crate::npc::{NpcId, RelationKind, Sex};
use crate::rng::SeedKey;

/// A person's place in their household.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Role {
    Head,
    Spouse,
    Child,
    Parent,
    Sibling,
    Lodger,
    Single,
}

/// One inhabitant in skeleton form.
#[derive(Debug, Clone)]
pub(crate) struct Person {
    pub building: usize,
    pub index: u32,
    pub household: usize,
    pub role: Role,
    pub race: usize,
    pub sex: Sex,
    pub age: u16,
    pub job: &'static str,
    pub workplace: Option<usize>,
    pub slot: Option<usize>,
    pub notable: bool,
}

/// One household in skeleton form. `relations` holds `(a, kind, b)`
/// meaning "b is a's kind", with both directions present.
#[derive(Debug, Clone)]
pub(crate) struct House {
    pub building: usize,
    pub index: u32,
    pub members: Vec<usize>,
    pub relations: Vec<(usize, RelationKind, usize)>,
}

/// The whole skeleton of one settlement.
pub(crate) struct Plan<'a> {
    pub data: &'static Data,
    pub seed: u64,
    pub settlement: &'a SettlementProfile,
    pub buildings: Vec<&'a BuildingSpec>,
    pub tier: &'static TierData,
    /// Languages the people are named in (`names.rs`).
    pub tongues: Tongues,
    /// Notable slots from the society layer.
    pub notables: &'a [NotableSlot],
    /// Slot index bound to each person (`slots.rs`).
    pub bound: Vec<Option<usize>>,
    pub ancestry: Vec<(usize, u32)>,
    pub people: Vec<Person>,
    pub offsets: Vec<usize>,
    pub houses: Vec<House>,
    pub slots: Vec<Vec<Option<usize>>>,
    pub friend: Vec<Option<usize>>,
    pub rival: Vec<Option<usize>>,
    /// Each building's workshop craft (`None` for other functions).
    pub crafts: Vec<Option<Craft>>,
    /// Public id of each person, in skeleton order.
    pub ids: Vec<NpcId>,
    /// `(id, person)` sorted by id, for lookups.
    pub by_id: Vec<(NpcId, usize)>,
}

impl<'a> Plan<'a> {
    /// Builds the skeleton.
    pub(crate) fn build(
        seed: u64,
        settlement: &'a SettlementProfile,
        input: &'a [BuildingSpec],
        notables: &'a [NotableSlot],
    ) -> Result<Self, NpcError> {
        let data = Data::get()?;
        let mut buildings: Vec<&BuildingSpec> = input.iter().collect();
        buildings.sort_by_key(|b| b.id);
        for pair in buildings.windows(2) {
            if pair[0].id == pair[1].id {
                return Err(NpcError::DuplicateBuilding(pair[0].id));
            }
        }
        if let Some(b) = buildings.iter().find(|b| b.settlement_id != settlement.id) {
            return Err(NpcError::ForeignBuilding {
                building: b.id,
                expected: settlement.id,
                found: b.settlement_id,
            });
        }
        let tier = data
            .tiers
            .tiers
            .get(settlement.tier.key())
            .ok_or_else(|| NpcError::Data(format!("no tier {}", settlement.tier.key())))?;
        let culture: &Culture = data
            .cultures
            .cultures
            .get(&settlement.culture)
            .or_else(|| data.cultures.cultures.get(&data.cultures.default))
            .ok_or_else(|| NpcError::Data("no default culture".into()))?;
        let weights = settlement
            .ancestry_mix
            .as_ref()
            .unwrap_or(&culture.ancestry);
        let ancestry: Vec<(usize, u32)> = weights
            .iter()
            .filter_map(|(key, &w)| {
                data.srd
                    .races
                    .iter()
                    .position(|r| r.key == *key)
                    .map(|i| (i, w))
            })
            .collect();
        if ancestry.iter().all(|&(_, w)| w == 0) {
            return Err(NpcError::Data("ancestry mix has no weight".into()));
        }
        let mut plan = Self {
            data,
            seed,
            settlement,
            buildings,
            tier,
            tongues: Tongues::new(seed, settlement),
            notables,
            bound: Vec::new(),
            ancestry,
            people: Vec::new(),
            offsets: Vec::new(),
            houses: Vec::new(),
            slots: Vec::new(),
            friend: Vec::new(),
            rival: Vec::new(),
            crafts: Vec::new(),
            ids: Vec::new(),
            by_id: Vec::new(),
        };
        plan.crafts = (0..plan.buildings.len()).map(|b| plan.craft(b)).collect();
        let occupancy = plan.occupancy()?;
        plan.populate(&occupancy)?;
        plan.assign_jobs()?;
        plan.pair_friends_and_rivals();
        plan.index_ids()?;
        Ok(plan)
    }

    /// Shares the population out over buildings in proportion to capacity
    /// (largest remainder, ties by building order).
    fn occupancy(&self) -> Result<Vec<u32>, NpcError> {
        let capacity: u64 = self.buildings.iter().map(|b| u64::from(b.capacity)).sum();
        let population = u64::from(self.settlement.population);
        if population > capacity {
            return Err(NpcError::NotEnoughHousing {
                population: self.settlement.population,
                capacity: u32::try_from(capacity).unwrap_or(u32::MAX),
            });
        }
        if population == 0 {
            return Ok(vec![0; self.buildings.len()]);
        }
        let mut occ: Vec<u32> = Vec::with_capacity(self.buildings.len());
        let mut rest: Vec<(u64, usize)> = Vec::with_capacity(self.buildings.len());
        for (i, b) in self.buildings.iter().enumerate() {
            let share = u64::from(b.capacity) * population;
            occ.push(u32::try_from(share / capacity).unwrap_or(0));
            rest.push((share % capacity, i));
        }
        let placed: u64 = occ.iter().map(|&o| u64::from(o)).sum();
        rest.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
        let missing = usize::try_from(population - placed).unwrap_or(0);
        for &(_, i) in rest.iter().take(missing) {
            occ[i] += 1;
        }
        Ok(occ)
    }

    /// Seed key of a building.
    pub(crate) fn building_key(&self, building: usize) -> SeedKey {
        let id = self
            .buildings
            .get(building)
            .map_or(BuildingId(u64::MAX), |b| b.id);
        SeedKey::building(self.seed, self.settlement.id, id)
    }

    /// Seed key of a person.
    pub(crate) fn person_key(&self, person: usize) -> SeedKey {
        let p = &self.people[person];
        self.building_key(p.building).with_index(p.index)
    }

    /// Staffing table of a building's function.
    pub(crate) fn workplace(&self, building: usize) -> Option<&'static WorkplaceData> {
        let function = self.buildings.get(building)?.function;
        self.data.occupations.workplaces.get(function.key())
    }

    /// SRD race of a person.
    pub(crate) fn race(&self, person: usize) -> &'static RaceData {
        let races = &self.data.srd.races;
        races.get(self.people[person].race).unwrap_or(&races[0])
    }

    /// A workshop's craft: its `craft:` tag, else one drawn from the
    /// building's own seed key (`logic/10` §town-building-spec).
    fn craft(&self, building: usize) -> Option<Craft> {
        let spec = self.buildings.get(building)?;
        if spec.function != BuildingFunction::Workshop {
            return None;
        }
        spec.craft_tag().or_else(|| {
            self.building_key(building)
                .rng("craft")
                .pick(&Craft::ALL)
                .copied()
        })
    }

    /// Computes every public id and the lookup table, refusing a collision.
    fn index_ids(&mut self) -> Result<(), NpcError> {
        let ids: Vec<NpcId> = self
            .people
            .iter()
            .map(|p| NpcId::from_parts(self.settlement.id, self.buildings[p.building].id, p.index))
            .collect();
        let mut by_id: Vec<(NpcId, usize)> = ids.iter().copied().zip(0..).collect();
        by_id.sort_unstable();
        if let Some(pair) = by_id.windows(2).find(|w| w[0].0 == w[1].0) {
            return Err(NpcError::Data(format!("npc id collision on {}", pair[0].0)));
        }
        self.ids = ids;
        self.by_id = by_id;
        Ok(())
    }

    /// Public id of a person.
    pub(crate) fn id_of(&self, person: usize) -> NpcId {
        self.ids.get(person).copied().unwrap_or_default()
    }

    /// Skeleton index of a public id.
    pub(crate) fn index_of(&self, id: NpcId) -> Result<usize, NpcError> {
        self.by_id
            .binary_search_by_key(&id, |&(k, _)| k)
            .map(|i| self.by_id[i].1)
            .map_err(|_| NpcError::UnknownNpc(id))
    }

    /// Skeleton index of the `index`-th resident of `building`.
    pub(crate) fn resident(&self, building: BuildingId, index: u32) -> Option<usize> {
        let b = self
            .buildings
            .binary_search_by_key(&building, |b| b.id)
            .ok()?;
        let i = self.offsets[b] + usize::try_from(index).ok()?;
        (i < self.offsets[b + 1]).then_some(i)
    }

    /// Buildings of a function, in id order.
    pub(crate) fn buildings_with(&self, pred: impl Fn(BuildingFunction) -> bool) -> Vec<usize> {
        (0..self.buildings.len())
            .filter(|&i| pred(self.buildings[i].function))
            .collect()
    }
}
