//! TypeScript bindings for every wire type, generated with ts-rs.
//!
//! The committed files live in `bindings/ts/arda/` at the workspace root.
//! `cargo test -p arda-server bindings` fails when they are stale; rerun it
//! with `ARDA_BLESS_BINDINGS=1` to rewrite them, then commit the diff.

use crate::columnar::{AreaCells, AreaColumns, Legend};
use crate::contract::{
    CellSample, CoastSample, CoverDto, FineHeights, HeightSource, LakeMembership, PointSample,
    RiverMembership, RoadDto, SnowSample, TerrainKindDto, CONTRACT_VERSION,
};
use crate::dto::{
    AreaLakes, AreaRivers, FineTerrainDto, Health, LakeDto, LatitudeDto, RiverDto, SizeKmDto,
    TerminusDto, TilePyramidDto, WorldInfo, API_VERSION,
};
use crate::error::{ApiError, ApiErrorBody, NotYetError, ServerError, ServerResult};
use crate::npc_dto as npc;
use crate::tactical::dto::{
    AssetClassDto, AssetRefDto, EdgeAxisDto, LightSourceDto, PlacementDto, SquareDto,
    TacticalBlockDto, TacticalLayoutDto, TacticalLayoutSummary, TacticalLayouts, TacticalTilesDto,
    WallRoleDto, WallSegmentDto,
};
use crate::tactical::library_dto::{GroundKeyDto, LibraryAssetDto, TacticalLibraryDto, WallKitDto};
use crate::tactical::rules_dto::{
    CoverLevelDto, EdgeRoleDto, EdgeRuleDto, RulesCellDto, RulesSidecarDto,
};
use std::path::PathBuf;
use ts_rs::TS;

/// Workspace-relative directory of the committed bindings.
pub const BINDINGS_DIR: &str = "bindings/ts/arda";

/// The committed directory, resolved from this crate's manifest.
#[must_use]
pub fn bindings_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(BINDINGS_DIR)
}

fn one<T: TS + 'static>(cfg: &ts_rs::Config) -> ServerResult<(String, String)> {
    let text =
        T::export_to_string(cfg).map_err(|e| ServerError::Internal(format!("ts-rs: {e}")))?;
    Ok((format!("{}.ts", T::ident(cfg)), text))
}

macro_rules! exported {
    ($($t:ty),* $(,)?) => {
        /// Every exported file as `(file name, contents)`, sorted by name, plus `index.ts`.
        ///
        /// # Errors
        /// [`ServerError::Internal`] if ts-rs cannot render a type.
        pub fn render() -> ServerResult<Vec<(String, String)>> {
            let cfg = ts_rs::Config::new();
            let mut files = vec![$( one::<$t>(&cfg)? ),*];
            files.sort();
            let mut index = String::from(
                "// Generated by arda-server (src/bindings.rs). Do not edit by hand.\n\n",
            );
            index.push_str(&format!("export const CONTRACT_VERSION = {CONTRACT_VERSION};\n"));
            index.push_str(&format!("export const API_VERSION = \"{API_VERSION}\";\n\n"));
            for (name, _) in &files {
                let stem = name.trim_end_matches(".ts");
                index.push_str(&format!("export type {{ {stem} }} from \"./{stem}\";\n"));
            }
            files.push(("index.ts".to_owned(), index));
            Ok(files)
        }
    };
}

exported!(
    TerrainKindDto,
    CoverDto,
    RoadDto,
    CoastSample,
    SnowSample,
    RiverMembership,
    LakeMembership,
    FineHeights,
    CellSample,
    HeightSource,
    PointSample,
    ApiError,
    ApiErrorBody,
    SizeKmDto,
    LatitudeDto,
    FineTerrainDto,
    TilePyramidDto,
    WorldInfo,
    Health,
    TerminusDto,
    RiverDto,
    LakeDto,
    AreaRivers,
    AreaLakes,
    Legend,
    AreaColumns,
    AreaCells,
    npc::NpcId,
    npc::HouseholdId,
    npc::Sex,
    npc::Name,
    npc::JobCategory,
    npc::Job,
    npc::SocialRank,
    npc::Lifestyle,
    npc::Ideal,
    npc::Personality,
    npc::RelationKind,
    npc::Relationship,
    npc::Npc,
    npc::HouseholdRelation,
    npc::Household,
    npc::RosterEntry,
    npc::Population,
    npc::PopulationRequest,
    npc::NpcDemo,
    npc::Tier,
    npc::SettlementFunction,
    npc::Biome,
    npc::SettlementProfile,
    npc::Tongue,
    npc::BuildingFunction,
    npc::BuildingSpec,
    npc::Ability,
    npc::SheetKind,
    npc::Background,
    npc::SaveBonus,
    npc::SkillBonus,
    npc::AttackKind,
    npc::Attack,
    npc::Item,
    npc::Coins,
    npc::SpellRef,
    npc::Spellcasting,
    npc::Sheet,
    NotYetError,
    TacticalLayouts,
    TacticalLayoutSummary,
    TacticalTilesDto,
    TacticalBlockDto,
    TacticalLayoutDto,
    SquareDto,
    EdgeAxisDto,
    WallRoleDto,
    AssetClassDto,
    WallSegmentDto,
    AssetRefDto,
    PlacementDto,
    LightSourceDto,
    RulesSidecarDto,
    RulesCellDto,
    EdgeRuleDto,
    EdgeRoleDto,
    CoverLevelDto,
    TacticalLibraryDto,
    GroundKeyDto,
    WallKitDto,
    LibraryAssetDto,
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_bindings_are_fresh() {
        let dir = bindings_dir();
        let files = render().unwrap();
        if std::env::var_os("ARDA_BLESS_BINDINGS").is_some() {
            std::fs::create_dir_all(&dir).unwrap();
            for entry in std::fs::read_dir(&dir).unwrap() {
                std::fs::remove_file(entry.unwrap().path()).unwrap();
            }
            for (name, text) in &files {
                std::fs::write(dir.join(name), text).unwrap();
            }
        }
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("{}: {e}; bless with ARDA_BLESS_BINDINGS=1", dir.display()))
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        on_disk.sort();
        let mut expected: Vec<String> = files.iter().map(|(n, _)| n.clone()).collect();
        expected.sort();
        assert_eq!(
            on_disk, expected,
            "stale file set; rerun with ARDA_BLESS_BINDINGS=1"
        );
        for (name, text) in &files {
            let committed = std::fs::read_to_string(dir.join(name)).unwrap();
            assert_eq!(
                &committed, text,
                "{name} is stale; rerun with ARDA_BLESS_BINDINGS=1"
            );
        }
    }

    #[test]
    fn u64_ids_are_strings_not_bigints() {
        let files = render().unwrap();
        assert!(files.iter().all(|(_, text)| !text.contains("bigint")));
        let cell = &files.iter().find(|(n, _)| n == "CellSample.ts").unwrap().1;
        assert!(cell.contains("fine: FineHeights | null"), "{cell}");
    }

    #[test]
    fn npc_types_are_exported_with_string_ids() {
        let files = render().unwrap();
        let text = |name: &str| {
            files
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, t)| t.clone())
                .unwrap_or_else(|| panic!("{name} is not exported"))
        };
        for name in [
            "Npc.ts",
            "Sheet.ts",
            "Population.ts",
            "SettlementProfile.ts",
            "BuildingSpec.ts",
        ] {
            text(name);
        }
        assert!(text("NpcId.ts").contains("export type NpcId = string;"));
        assert!(text("Npc.ts").contains("id: NpcId"));
        assert!(text("SettlementProfile.ts").contains("id: string"));
        assert!(text("BuildingSpec.ts").contains("tags?: Array<string>"));
        let index = text("index.ts");
        assert!(
            index.contains("export type { Npc } from \"./Npc\";"),
            "{index}"
        );
    }

    #[test]
    fn tactical_layout_binding_describes_the_layout_json() {
        let files = render().unwrap();
        let find = |n: &str| &files.iter().find(|(f, _)| f == n).unwrap().1;
        let layout = find("TacticalLayoutDto.ts");
        assert!(layout.contains("squares: Array<SquareDto>"), "{layout}");
        let asset = find("AssetRefDto.ts");
        assert!(
            asset.contains("\"id\": string") && asset.contains("\"query\""),
            "{asset}"
        );
        assert!(find("NotYetError.ts").contains("planned_source: string"));
    }
}
