"""Generate deterministic Q60 trigonometric constants without binary floats."""
from decimal import Decimal, localcontext, ROUND_HALF_UP
from pathlib import Path
import sys

TARGET = Path(__file__).resolve().parents[1] / 'crates/arda-gen/src/spectral_tables.rs'

def atan(x):
    total = term = x
    for k in range(1, 1000):
        term *= -x*x
        add = term / (2*k+1)
        total += add
        if abs(add) < Decimal('1e-100'):
            return total
    raise ArithmeticError('arctangent did not converge')

def trig(x, sine=False):
    total = term = x if sine else Decimal(1)
    for k in range(1, 1000):
        term *= -x*x / ((2*k)*(2*k+1) if sine else (2*k-1)*(2*k))
        total += term
        if abs(term) < Decimal('1e-100'):
            return total
    raise ArithmeticError('trigonometric series did not converge')

def render():
    with localcontext() as ctx:
        ctx.prec = 110
        pi = 16*atan(Decimal(1)/5)-4*atan(Decimal(1)/239)
        def fixed(x):
            return int((x*(1 << 60)).to_integral_value(rounding=ROUND_HALF_UP))
        roots = [(fixed(trig(2*pi/(1 << k))), -fixed(trig(2*pi/(1 << k), True))) for k in range(1, 16)]
        quarter = [fixed(trig(pi*j/2048)) for j in range(1025)]
    assert roots[0] == (-(1 << 60),0) and roots[1] == (0,-(1 << 60))
    assert quarter[0] == 1 << 60 and quarter[-1] == 0
    assert all(a>b for a,b in zip(quarter,quarter[1:]))
    lines = ['// Generated by tools/generate_spectral_tables.py using Decimal arithmetic.',
             '// Q60 roots for radix-2 lengths 2..32768; cosine quarter at 4096 phases.',
             '', 'pub(crate) const ROOTS_Q60: [(i64, i64); 15] = [']
    lines += [f'    ({a}, {b}),' for a,b in roots]
    lines += ['];', '', 'pub(crate) const COS_QUARTER_Q60: [i64; 1025] = [']
    lines += [f'    {v},' for v in quarter]
    return '\n'.join(lines + ['];', ''])

if __name__ == '__main__':
    content = render()
    if sys.argv[1:] == ['--check']:
        assert TARGET.read_text() == content, 'spectral constants differ from generator'
        print('Spectral tables match their Decimal generator.')
    elif not sys.argv[1:]:
        TARGET.write_text(content)
        print(f'Wrote {TARGET}')
    else:
        raise SystemExit('usage: generate_spectral_tables.py [--check]')
