//! Field kinds, crops and the per-field record.

use crate::geom::{h2, u01, Sq, SQUARE_M};
use crate::input::{LandUse, Settlement, Tier};
use serde::Serialize;

/// Hectares per inhabitant of farmland (`mockup-artifact.md`).
pub const HA_PER_PERSON: f64 = 0.8;
/// Square metres per square.
pub const SQUARE_M2: f64 = SQUARE_M * SQUARE_M;

/// What a field is used for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldKind {
    /// A furlong of open-field strips near a village; unenclosed.
    Strips,
    /// An enclosed arable field.
    Arable,
    /// Enclosed grazing.
    Pasture,
    /// Enclosed hay meadow.
    Meadow,
    /// Enclosed fallow.
    Fallow,
    /// Enclosed orchard.
    Orchard,
    /// Woodland; unenclosed, with a scrub fringe.
    Woodland,
    /// Rough grazing, heath and scrub; unenclosed.
    Wild,
}

impl FieldKind {
    /// Whether the field is bounded by hedges or walls with gates.
    #[must_use]
    pub fn enclosed(self) -> bool {
        matches!(
            self,
            Self::Arable | Self::Pasture | Self::Meadow | Self::Fallow | Self::Orchard
        )
    }
}

/// What a field (or strip) looks like this season.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Crop {
    /// Freshly ploughed ridges and furrows.
    Ploughed,
    /// Cut cereal stubble with stooks.
    Stubble,
    /// Resting ground gone to weeds.
    Fallow,
    /// Standing hay.
    Hay,
    /// Mown hay meadow with bales.
    Mown,
    /// Grazed turf.
    Grazed,
    /// Nothing sown.
    None,
}

impl Crop {
    /// Ground key of the crop.
    #[must_use]
    pub fn ground(self) -> &'static str {
        match self {
            Self::Ploughed => "farmland",
            Self::Stubble => "stubble",
            Self::Fallow => "fallow",
            Self::Hay | Self::Mown => "meadow",
            Self::Grazed => "pasture",
            Self::None => "grass",
        }
    }

    /// An arable crop drawn from the rotation's shares.
    #[must_use]
    pub fn arable(u: f64) -> Self {
        if u < 0.45 {
            Self::Ploughed
        } else if u < 0.8 {
            Self::Stubble
        } else {
            Self::Fallow
        }
    }
}

/// One field: a connected parcel of squares with one use.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Field {
    /// Stable id from the site and the parcel's first square.
    pub id: u64,
    /// Use.
    pub kind: FieldKind,
    /// Crop (per strip for [`FieldKind::Strips`]).
    pub crop: Crop,
    /// Boundary wall kit, for enclosed fields.
    pub kit: &'static str,
    /// Area in squares.
    pub squares: u32,
    /// First square in row-major order.
    #[serde(skip)]
    pub first: Sq,
    /// Sum of square centres, for the centroid.
    #[serde(skip)]
    pub sum: [f64; 2],
    /// Index of the generating site.
    #[serde(skip)]
    pub site: usize,
}

impl Field {
    /// Area in hectares.
    #[must_use]
    pub fn hectares(&self) -> f64 {
        f64::from(self.squares) * SQUARE_M2 / 10_000.0
    }

    /// Centroid in square units.
    #[must_use]
    pub fn centroid(&self) -> [f64; 2] {
        let n = f64::from(self.squares.max(1));
        [self.sum[0] / n, self.sum[1] / n]
    }
}

/// Radius of a settlement's open fields, in squares: the disc holding its
/// 0.8 ha per inhabitant, slightly trimmed for commons and meadow.
#[must_use]
pub fn open_field_radius(s: &Settlement) -> f64 {
    if s.tier < Tier::Village {
        return 0.0;
    }
    let m2 = f64::from(s.population) * HA_PER_PERSON * 10_000.0;
    0.9 * (m2 / std::f64::consts::PI).sqrt() / SQUARE_M
}

/// The kind and crop of a field generated by a site of `class` at `p`.
#[must_use]
pub fn kind_of(
    class: Option<LandUse>,
    p: [f64; 2],
    settlements: &[Settlement],
    seed: u64,
    key: (i64, i64),
) -> (FieldKind, Crop) {
    let u = u01(h2(seed, 0xC209, key.0, key.1));
    let Some(class) = class else {
        return (FieldKind::Wild, Crop::None);
    };
    match class {
        LandUse::Arable => {
            let near_village = settlements.iter().any(|s| {
                let (sx, sy) = (s.x_m / SQUARE_M, s.y_m / SQUARE_M);
                let r = open_field_radius(s);
                (p[0] - sx).powi(2) + (p[1] - sy).powi(2) <= r * r
            });
            if near_village {
                (FieldKind::Strips, Crop::arable(u))
            } else {
                (FieldKind::Arable, Crop::arable(u))
            }
        }
        LandUse::Farmstead if u < 0.5 => (FieldKind::Pasture, Crop::Grazed),
        LandUse::Farmstead => (FieldKind::Arable, Crop::arable(u * 2.0 - 1.0)),
        LandUse::Pasture => (FieldKind::Pasture, Crop::Grazed),
        LandUse::Meadow | LandUse::Mill => {
            if u < 0.5 {
                (FieldKind::Meadow, Crop::Hay)
            } else {
                (FieldKind::Meadow, Crop::Mown)
            }
        }
        LandUse::Fallow => (FieldKind::Fallow, Crop::Fallow),
        LandUse::Orchard => (FieldKind::Orchard, Crop::Grazed),
        LandUse::Woodland => (FieldKind::Woodland, Crop::None),
        LandUse::MineQuarry => (FieldKind::Wild, Crop::None),
    }
}
